### ISSUE TITLE
Timeshift for radio channels

### ISSUE THREAD

**Issue by cuh7b5** [xbmc/inputstream.ffmpegdirect#101]
Hello,
On Arch linux, Kodi 19:
I have some mp3 radio streams in my m3u file like this:
```
#EXTINF:-1,tvg-logo="https://www.radio.net/images/broadcasts/88/e1/3244/1/c300.png" group-title="radio" radio="true",BBC Radio 2
http://stream.live.vc.bbcmedia.co.uk/bbc_radio_two

```
Thimeshift is enabled in the pvr client and works fine for TV streams. But for radio streams I get a strange behavior: I start the radio stream, leave it play for some seconds. Pressing the pause button then the play button, the stream starts playing from the beggining instead of pausing/resuming. Seeking forward and backward buttons result the same: the stream starts from the beggining (i.e. the point where I originally started the stream).

Is there a way to properly configure timeshift for radio channels?

Thanks!

**Comment by phunkyfish** [comment]
One issue is enough 😉
