### ISSUE TITLE
Ignoring header option

### ISSUE THREAD

**Issue by Vikassm73** [xbmc/inputstream.ffmpegdirect#107]
Tried this after inputstream.adaptive failed to play

Passed hls url with header information in piped. getting following error. it seems that it is ignoring header information. Please advise.
Also, does inputstream.ffmpegdirect.stream_headers works?

21-06-06 13:28:40.853 T:14540   DEBUG <general>: CDVDDemuxFFmpeg::GetFFMpegOptionsFromInput() ignoring header option 'Content-Type'
2021-06-06 13:28:40.853 T:14540   DEBUG <general>: CDVDDemuxFFmpeg::GetFFMpegOptionsFromInput() ignoring header option 'app_version'
2021-06-06 13:28:40.853 T:14540   DEBUG <general>: CDVDDemuxFFmpeg::GetFFMpegOptionsFromInput() ignoring header option 'security_token'
2021-06-06 13:28:40.854 T:14540   DEBUG <general>: CDVDDemuxFFmpeg::GetFFMpegOptionsFromInput() adding ffmpeg option 'user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36'
2021-06-06 13:28:40.854 T:14540   DEBUG <general>: CDVDDemuxFFmpeg::GetFFMpegOptionsFromInput() ignoring header option 'x-playback-session-id'
2021-06-06 13:28:40.854 T:14540   DEBUG <general>: CDVDDemuxFFmpeg::GetFFMpegOptionsFromInput() ignoring header option 'x-via-device'
2021-06-06 13:28:40.854 T:14540   DEBUG <general>: XCURL::DllLibCurlGlobal::easy_acquire - Created session to https://sonynondrmvod.akamaized.net
2021-06-06 13:28:42.204 T:14540   DEBUG <general>: ffmpeg[0x223295dd090X]: [https] HTTP error 403 Forbidden

**Comment by phunkyfish** [comment]
You would need to provide the url you try to play and how you tried to play it.

a full debug log would also be helpful.

**Comment by Vikassm73** [comment]
Please find the full Kodi log

[kodiLog.log](https://github.com/xbmc/inputstream.ffmpegdirect/files/6604189/kodiLog.log)


stream_url='https://sonynondrmvod.akamaized.net/4338955589001_4931928643001_4931911563001.m3u8?hdnea=exp=1623025867~acl=/*~id=90862381920848353533327135080787~hmac=27b90d161c3390c013fce49760c20b76d04a8b70ef57ac3303b0d125542f5baa&c3.ri=6908534796634411304|Content-Type=application%2Fjson&x-via-device=true&app_version=3.2.30&security_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjI5ODI2MjksImV4cCI6MTYyNDI3ODYyOSwiYXVkIjoiKi5zb255bGl2LmNvbSIsImlzcyI6IlNvbnlMSVYiLCJzdWIiOiJzb21lQHNldGluZGlhLmNvbSJ9.OwWXOgb3Q3oOf9Jzoe7Eh7X_up7QhSwYGd8tfXlwLwwrzxoRMTWQoFZP6TSdkIcyVr9sAG99MlL66Q344ncbAsRxkjgDvF8J6bghaCyszTIQNmQKSu3wggz9hFdM4pjSd9ksp3nXPWqpgbl_u7H2nwyKcA4vsHIEtmfcQ5XNI6u7a14gP9oFgWCFjFPCiCLYW-4463qRu06qd6fGeMS2uBsjjTCg-FgVU05VRDaaiwNb-5Trey86w6QxGtuQeDoOoI5QdHkDG2DGlG4sdrmN3iGk1Pk90362CzXJr1rdxocV-W-ZyzemPMeQILVpJjFpfm9Hk1hVgF0E-AkjGzFdOSJm7kcxdCnMP-X9OgJnt5OMKdQwHRK2KQ0bJ30XHumVO8M1hFQpXhFe2KvCkHwUnXq3h6Q9VhgAUTYnkXRNP2_rOtreDCXghiceLDHk8CyRc0AKGaE4BO0yoQVF2vnk56sR21LOHHc6hdbUHe2cS-QXNo0tltTmUa3BYBNZ-8dHoNvqNMrUWfTnT55RNJl01GCFWit_64Ypf-qOS9bJEI96VZIqMPABCb6Fl-Bn_mQL8PVU2MA0QOBY69DUTxoJscr9kSzWboKY4nq-qUcH_uM6l495gA4EMTxUdUSYww0kehozFQKrxSvrqUtmc0KD5R7_3L4z4BncNrVPAHB_CiM&x-playback-session-id=b3751171afcb441a865c018433ff3534-1622824103229&user-agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F91.0.4472.77+Safari%2F537.36'

    play_item = xbmcgui.ListItem(path=stream_url)
    play_item.setPath(stream_url)
    play_item.setProperty('inputstreamaddon', 'inputstream.ffmpegdirect')
    play_item.setProperty('inputstream.ffmpegdirect.manifest_type', 'hls')
    play_item.setMimeType('application/vnd.apple.mpegurl')    
    play_item.setContentLookup(False)
    xbmcplugin.setResolvedUrl(_handle, True, listitem=play_item)

**Comment by Vikassm73** [comment]
Also tried to pass header information using 
phdr=headers
play_item.setProperty('inputstream.ffmpegdirect.stream_headers', urllib_parse.urlencode(phdr))

instead of using URL separated pipe but that doesn't work

**Comment by phunkyfish** [comment]
There is no such thing as headers for ffmpegdirect.

only the options in the readme are supported.

does this play in vlc or some other player ok?

**Comment by Vikassm73** [comment]
It plays perfectly in Leia version using IA

**Comment by phunkyfish** [comment]
Please raise this issue on the IA GitHub.

**Comment by Vikassm73** [comment]
Ok thanks
