### ISSUE TITLE
How does this differ from the original inputstream plugin?

### ISSUE THREAD

**Issue by ilikenwf** [xbmc/inputstream.ffmpegdirect#163]
There's nothing in your readme.md describing the differences in this fork.

**Comment by phunkyfish** [comment]
It’s in the first two paragraphs of the readme:

“This is a Kodi input stream addon for streams that can be opened by either FFmpeg's libavformat or Kodi's cURL. Common stream formats such as plain TS, HLS and DASH are supported as well as many others. Note that the only DASH streams supported are those without DRM.

The addon also has support for Archive/Catchup services where there is a replay window (usually in days) and can timeshift across that span. In addition the addon can also provide timeshift to live streams where rewind/pause and fast-forward woud not have previously been possible.”
