### ISSUE TITLE
Inputstream FFmpegDirect incompatibility with Kodi 20 "Nexus" Alpha 1

### ISSUE THREAD

**Issue by FrankVan1982** [xbmc/inputstream.ffmpegdirect#176]
Hi, I have a problem. Oddly I just installed Kodi 20 "Nexus" Alpha 1, and I notice that the add-on is not compatible.

**Comment by phunkyfish** [comment]
Yes, there was a recent API change. What platform?

**Comment by phunkyfish** [comment]
What platform are enough running.

**Comment by FrankVan1982** [comment]
Android
(Samsung Galaxy Tab A - Android 11 R)

**Comment by phunkyfish** [comment]
There was a build error for Android. It will be there once the PR is built and release.

**Comment by linuxkodi** [comment]
Also a problem under Xubuntu.

**Comment by schmidchr** [comment]
add-on used to work, yet after update to 
Kodi Media Center 20.0 (20.0.0) Git:20230115-389e701cb9 on Ubuntu 22.04
pull from git and make compilation without errors
-> Kodi arequests to install inputstream-FFmpeg, but then fails with message:
"The add-on is not compatible with this version of Kodi"
-> any advice?

**Comment by lrusak** [comment]
> add-on used to work, yet after update to 
> 
> Kodi Media Center 20.0 (20.0.0) Git:20230115-389e701cb9 on Ubuntu 22.04
> 
> pull from git and make compilation without errors
> 
> -> Kodi arequests to install inputstream-FFmpeg, but then fails with message:
> 
> "The add-on is not compatible with this version of Kodi"
> 
> -> any advice?

Do you have another version installed already? Otherwise please use the forum for support. https://forum.kodi.tv/

**Comment by schmidchr** [comment]
thanks for the rapid response. Another version of what? 
Kodi 19.5 on Ubuntu 22.04 works perfectly fine with the inputstream-FFmpeg add-on.
A related thread: https://forum.kodi.tv/showthread.php?tid=371332

**Comment by phunkyfish** [comment]
Do you have v19 addons installed in kodi 20?

**Comment by schmidchr** [comment]
the solution is kinda obvious, once you figure it out :)
 `git switch Nexus` 

more extensive to help others: there are specific branches for each Kodi release!
-> only `git pull` on a previous local copy retrieves the latest add-on, but for the Kodi release set as default at the time.
Thanks, now inputstream-FFmpeg working flawless with Kodi 20 on Ubuntu 22.04
