### ISSUE TITLE
Android Sound Stutter changing Audio Source from 5.1 to 2.0

### ISSUE THREAD

**Issue by Starfoxfs** [xbmc/inputstream.ffmpegdirect#199]
I installed Kodi 20 Nexus freshly on a Fire TV 4k Max and I have the problem that whenever the audio source in an IPTV stream changes from 5.1 to 2.0 (e.g. by changing channels), the sound stutters and my receiver gets stuck on 5.1 channels and not change to 2.0.

I think its a Coded Problem but i don´t know.

Only if Kodi´s Audio Output Configuration is set to "Optimized" or "Best Match" with 5.1 Channels

The same problem occurs in 19.4 Matrix and 18.9 Leia with older FFMpeg Versions

The Issue occurs only from changing 5.1 to 2.0 Audio Sources
Changing the Streams from 2.0 to 2.0 Audio works or 5.1 to 5.1 or 2.0 to 5.1 works.

I added a Kodi.log here, RTLNitro 5.1 Channels works ok, then I switch to Tele5 with 2.0 Audio Source and there it stutters.
[kodi.log](https://github.com/xbmc/inputstream.ffmpegdirect/files/9320849/kodi.log)

**Comment by phunkyfish** [comment]
This should be raised on the xbmc GitHub. Inputstream.ffmpegdirect did not exist at the time of Kodi 18.

**Comment by Starfoxfs** [comment]
Ok thanks
