### ISSUE TITLE
[Help] Cross compile for android armv7

### ISSUE THREAD

**Issue by Mio-sha512** [xbmc/inputstream.ffmpegdirect#213]
Hi,

I'm a bit of a noob when it comes to this stuff and couldn't anything about how to cross-compile Kodi addons when I googled.

So I'm humbly asking for some help with compiling for android Armv7.

Thanks in advance

**Comment by basilgello** [comment]
The artifacts are there: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.ffmpegdirect/detail/PR-214/1/artifacts

**Comment by lrusak** [comment]
Please use the forum for support.

https://forum.kodi.tv/


https://github.com/xbmc/xbmc/blob/master/docs/README.Android.md

**Comment by phunkyfish** [comment]
All you need is a PR and you can also get the artifacts from Jenkins.
