### ISSUE TITLE
Compil issue

### ISSUE THREAD

**Issue by bibitocarlos** [xbmc/inputstream.ffmpegdirect#224]
Hi,

I tried to compil following the guide, but i get an error :

`[ 88%] Performing build step for 'ffmpeg'
[ 75%] Performing build step for 'ffmpeg'
CC	libavutil/hwcontext_vulkan.o
src/libavutil/hwcontext_vulkan.c:363:7: erreur: « VK_EXT_VIDEO_DECODE_H264_EXTENSION_NAME » non déclaré ici (hors de toute fonction); vouliez-vous utiliser « VK_EXT_VIDEO_ENCODE_H264_EXTENSION_NAME » ?
  363 |     { VK_EXT_VIDEO_DECODE_H264_EXTENSION_NAME,                FF_VK_EXT_NO_FLAG                },
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |       VK_EXT_VIDEO_ENCODE_H264_EXTENSION_NAME
src/libavutil/hwcontext_vulkan.c:364:7: erreur: « VK_EXT_VIDEO_DECODE_H265_EXTENSION_NAME » non déclaré ici (hors de toute fonction); vouliez-vous utiliser « VK_EXT_VIDEO_ENCODE_H265_EXTENSION_NAME » ?
  364 |     { VK_EXT_VIDEO_DECODE_H265_EXTENSION_NAME,                FF_VK_EXT_NO_FLAG                },
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |       VK_EXT_VIDEO_ENCODE_H265_EXTENSION_NAME
src/libavutil/hwcontext_vulkan.c:4163:1: erreur fatale: ouverture du fichier de dépendances libavutil/hwcontext_vulkan.d: Permission non accordée
 4163 | };
      | ^
compilation terminée.
`

Any idea ?

**Comment by lrusak** [comment]
disable vulkan in the ffmpeg options or remove vulkan headers from your system.

Please use the forums for support. https://forum.kodi.tv/
