### ISSUE TITLE
Increase waiting time for slow streams start

### ISSUE THREAD

**Issue by osscombat** [xbmc/inputstream.ffmpegdirect#259]
Hi,
Hope this is the right place for this issue. I use IPTV simple client, and with some HLS streams that are not so fast Kodi hangs in buffering, and that drops the stream. Is it possible to increase this waiting time somehow, since many other players are hanging on waiting for the same streams just fine?

**Comment by phunkyfish** [comment]
Do you have a full debug log illustrating the problem?

**Comment by osscombat** [comment]
n/a
