### ISSUE TITLE
[Support] Play timeshift buffer backup as regular video

### ISSUE THREAD

**Issue by pal1000** [xbmc/inputstream.ffmpegdirect#291]
I know for a fact that kodi is prone to freeze under memory starvation conditions. To save the timeshift buffer I backed it up to a different location before terminating kodi process. How do I play it? There is no live stream involved.

**Comment by phunkyfish** [comment]
You cannot I’m afraid. Playback of a timeshift buffer is only possible when a stream is playing.

**Comment by pal1000** [comment]
I can restart the stream but obviously it will create a new timeshift buffer from scratch with new ID.

**Comment by phunkyfish** [comment]
Correct, a timeshift buffer can only be used with the currently playing stream.

**Comment by pal1000** [comment]
That's an unpleasant limitation considering its layout is similar to a basic segmented video.

**Comment by phunkyfish** [comment]
It is by design, so the buffer can’t be used as a form of recording. If a catchup type playback is required by the user it must be provided by the streaming service, but not via kodi built in functionality.
