### ISSUE TITLE
Timeshift causes crash on rewind

### ISSUE THREAD

**Issue by ghost** [xbmc/inputstream.ffmpegdirect#307]
I am running Kodi 21 and inpuststream.ffmpegdirect 21.3.5 along with ISA. When I pause a live non-Widevine stream through IPTV Simple and then I hit the rewind button, kodi ends up freezing and crashing. Not that I'm looking to rewind but sometimes I hit the rewind button by accident or the seek 10 seconds back. Maybe the buffer doesn't have 10 seconds worth hence the crash?

inputstream.ffmpegdirect: LoadSegment - segment load error, packet index 32766 does not equal expected value of 921 with a total packet count of: 922

**Comment by phunkyfish** [comment]
Provide a full debug log capturing the crash please.

**Comment by ghost** [comment]
Here is a link to the debug log file.

https://pastebin.ai/xcklaya7cv

**Comment by ghost** [comment]
I installed Gentoo along with Kodi 22.0 and the ffmpedirect for version 22 and I don't have any problems.

**Comment by phunkyfish** [comment]
Great!
