### ISSUE TITLE
Changing Displayed Start/Progress/End Times of a RTP Stream

### ISSUE THREAD

**Issue by KasparWinckler** [xbmc/inputstream.ffmpegdirect#311]
Hello,

Thank you for the inputstream.ffmpegdirect addon.

I am writing an addon that plays a rtp stream (rtp://address:port). By default, Kodi only shows a progress time, that corresponds to how long the stream has been playing. I am wondering if it is possible to replace this default progress time by start/progress/end times that would be provided by the addon, in a way comparable to how Kodi displays the times of a live TV programme.

My addon is written in Python and uses the following list item properties:
```
list_item.setProperties(
    {
        "inputstream": "inputstream.ffmpegdirect",
        "mimetype": "audio/pcm;big-endian=true;channels=2;rate=44100",
    }
)
```

Thank you for your help with this.

**Comment by phunkyfish** [comment]
Have you opened the stream as a live stream? Not sure what the property is in python but some like `isRealtime` should be available. Set that to false.

otherwise things you could try:

- see if it plays without ffmpeg direct
- See if it plays with inputstream.rtmp
- Try it with timeshift enabled for ffmpegdirect. This should hopefully work with RTP streams. But it’s not supported, but still worth a try

**Comment by KasparWinckler** [comment]
Thank you for your help.

- `inputstream.rtmp` does not work.
- `ìnputstream.ffmpeg` works.
  Setting properties `isrealtimestream` or `ìnputstream.ffmpeg.isrealtimestream` to `false` does not change how Kodi displays playback.
  I have no idea who to ask how to change start/progress/end times with this inpustream.
- `ìnputstream.ffmpegdirect` works.
  Setting the property `inputstream.ffmpegdirect.is_realtime_stream` to `false` removes the backward/forward input buttons.
  Setting the property `inputstream.ffmpegdirect.stream_mode` to `timeshift` buffers the stream, which in my opinion is not desirable.
  Settings `inputstream.ffmpegdirect.programme_start_time` and `inputstream.ffmpegdirect.programme_end_time` do not appear to have any effect on how Kodi displays playback.

**Comment by phunkyfish** [comment]
Can you provide some screenshots of how it is currently vs how you want it to be?

programme start and end time will have no effect. They are only used for catchup streams.

**Comment by KasparWinckler** [comment]
This is what I have
![screenshot00002](https://github.com/user-attachments/assets/2dcfa61b-728e-4d56-84ff-6356942d6d41)

This is what it could be (if possible, start time could be zero, and end time a duration)
![screenshot00000](https://github.com/user-attachments/assets/ed5a4a7c-b920-4a0b-8e0a-16e35c933234)

In fact, I would like to update progress and duration on the fly, e.g., start time is 0, progress is 01:23, duration is 04:56.

**Comment by phunkyfish** [comment]
Ah, so this is all audio?

**Comment by phunkyfish** [comment]
I assume you can’t seek the steam at all? 

Is this actually a live stream? Or is it discreet stream with a start and end?

**Comment by KasparWinckler** [comment]
It is all audio, and a continuous stream (much like a PVR live TV programme). The stream can't be seeked.

I notice I forgot an important point. My addon starts playback with `xbmc.Player.play()` and updates information with `xbmc.Player.updateInfoTag()` in order to avoid restarting gapless playback.

**Comment by phunkyfish** [comment]
If it’s a continuous stream the inputstream won’t know where it ends. It will just keep streaming.

In PVR an EPG is used to overlay programmes via video player.

is what you are trying to do similar to an EPG in PVR? 

I’m not sure what you are looking to do is achievable via an inputstream. Taking pvr.iptvsimple as an example, all that happens there is we pass the stream to the inputstream and then VideoPlayer takes it from there.

**Comment by KasparWinckler** [comment]
Ideally, I would like to be able to, within a Python script, set the progress time displayed by Kodi to a specific time, that corresponds to a position in a track, without interrupting playback, i.e., updating the Player.Time infolabel. I understand from our conversation that an inputstream is probably not the best way of achieving this. Do you have a suggestion where I could ask further help?

**Comment by phunkyfish** [comment]
I would probably ask in the kodi dev forums. This must be a common problem for video and audio addons

**Comment by KasparWinckler** [comment]
xbmc.Player.seekTime() does the trick, even though the stream is not seekable.
I consider my problem solved.
Thank you for help.
