### ISSUE TITLE
Detect EOF in demuxer - Implement reconnection

### ISSUE THREAD

**Issue by phunkyfish** [xbmc/inputstream.ffmpegdirect#38]
When a stream reaches the end of a stream it will execute the following code in VideoPlayer:

https://github.com/xbmc/xbmc/blob/7af85a0fbcfddd3516ea26a8e27e48d9d4eddc73/xbmc/cores/VideoPlayer/VideoPlayer.cpp#L1490-L1501

Need to figure out what the correct method of detection should be to catch this in the demuxer.

**Comment by phunkyfish** [comment]
@FernetMenta 

Is this as simple as if the stream demux speed is not 0 and we have stopped reading data for X seconds that we can assume an EOF?

So similar to the timer mechanism used in RTMP to detect a pause.

**Comment by FernetMenta** [comment]
Reading no data does not necessarily mean eof. Live TV for example has no eof. No data could mean that there is currently no signal.

**Comment by phunkyfish** [comment]
Ok, it may not necessarily mean that but what heuristic could we have for this?

I know that when viewing my pvr setup remotely my data speed can be insufficient for a time and VP stops playing. 

If I could detect that I could reconnect without having to physically play the channel again.

Is it possible to tell the difference between no signal and no data? Or to the demuxer will they look the same?

**Comment by phunkyfish** [comment]
What about this. If no data is read in 5 seconds and during that 5 seconds speed has been non zero then it could be a potential EOF. Could be a bit cleverer based on the rate VP would have read it's buffer based on the demux speed. Or maybe the 5 seconds is based on the demux speed. The idea being to calculate a time period where VP would need to request data to fill its buffer.

The demuxer could be configurable to allow this feature or not as desired by the client. If/when gRPC is implemented the client could also notify the inputstream if no signal was detected so disable the feature temporarily.

Thoughts? Does that sound like a reasonable heuristic?

**Comment by FernetMenta** [comment]
I consider every assumption based on time not good. EOF conditions are well defined, i.e. read last byte of a file, connection to server terminated, server indicated eof, etc. If none of the clear eof conditions apply, I would keep VP going by submitting empty packets. PVR channels are not supposed to terminate due to eof. If there is a thunderstorm between the satellite and my dish, I don't want the channel to terminate even if the condition lasts for some minutes.

**Comment by phunkyfish** [comment]
Ok, great advice, thanks as always.

So in the case of the ffmpeg demuxer the state of these known conditions would be turned in `m_pkt.result`?

Or do I need to check elsewhere?

**Comment by phunkyfish** [comment]
NVM, that is how it works.

Thanks once more for your guidance!

**Comment by rafhtl** [comment]
I have the exact same problem
Process - eof reading from demuxer
2021-03-30 23:24:13.721 T:9160     INFO <general>: CVideoPlayer::OnExit()
2021-03-30 23:24:13.721 T:9160     INFO <general>: VideoPlayer: eof, waiting for queues to empty
2021-03-30 23:24:13.721 T:9160     INFO <general>: Closing stream player 1

Stream just stops and exits
any suggestions?
pvr.iptvsimple
rpi4 kodi19
thank you

**Comment by phunkyfish** [comment]
> I have the exact same problem
> Process - eof reading from demuxer
> 2021-03-30 23:24:13.721 T:9160 INFO : CVideoPlayer::OnExit()
> 2021-03-30 23:24:13.721 T:9160 INFO : VideoPlayer: eof, waiting for queues to empty
> 2021-03-30 23:24:13.721 T:9160 INFO : Closing stream player 1
> 
> Stream just stops and exits
> any suggestions?
> pvr.iptvsimple
> rpi4 kodi19
> thank you

Sorry, this was an issue created regarding figuring out how detect an EOF and implement reconnection in the add-on so your issue could not be related.

It sounds like your issue is not a bug to be raised on GitHub but instead it is a support question that should be raised on the kodi forum.
