### ISSUE TITLE
Release 1.9.1 doesn't install on recent Magtrix nightlies

### ISSUE THREAD

**Issue by devilsport** [xbmc/inputstream.ffmpegdirect#42]
Kodi (19.0-ALPHA1 Git:20200422-cdb887b088). Platform: Windows NT x86 64-bit

`CAddonInstallJob[inputstream.ffmpegdirect]: The dependency on kodi.binary.instance.inputstream version 2.3.0 could not be satisfied.`

Cheers.

**Comment by phunkyfish** [comment]
There was an API change today. It will install on the next nightly build.

**Comment by devilsport** [comment]
Cool thanks for the info.
