### ISSUE TITLE
Slow channel switch time

### ISSUE THREAD

**Issue by vpeter4** [xbmc/inputstream.ffmpegdirect#57]
Because Kodi Matrix becomes more mature I finally decided to test my live TV setup on it. Functionality worked ok but I was disappointed with channel switch time. Because same thing happen with Kodi Leia I know I have to look for some realtime things in the code. And I found some inconsistence in **pvr.iptvsimple** and **inputstream.ffmpegdirect**.

The first problem I found was in pvr.iptvsimple where realtime property is hardcoded to true here https://github.com/kodi-pvr/pvr.iptvsimple/blob/Matrix/src/iptvsimple/CatchupController.cpp#L184
`catchupProperties.insert({"inputstream.ffmpegdirect.is_realtime_stream", "true"});`

In my opinion it should use channel property like this:
`catchupProperties.insert({"inputstream.ffmpegdirect.is_realtime_stream", StringUtils::EqualsNoCase(channel.GetProperty(PVR_STREAM_PROPERTY_ISREALTIMESTREAM), "true") ? "true" : "false"});
`

This way realtime property is correctly transfered to inputstream.ffmpegdirect.

But there is another issue where realtime property is not used properly here https://github.com/xbmc/inputstream.ffmpegdirect/blob/Matrix/src/stream/FFmpegStream.cpp#L594:
`return m_isRealTimeStream || m_pFormatContext->duration <= 0;`

Even if realtimestream is set to false this function can (and does) return true. Maybe instead of **||** should be used **&&** ?

When this two changes are applied I get much faster channel switch time.

**Comment by phunkyfish** [comment]
Thanks for this. Question. Why would you want `is_realtime_stream` to be set to anything else but `true`? Catchup streams only work with streams that are live so false should not be possible. Or maybe this is a new use case I have not encountered before. If that is the case then this change makes perfect sense.

On the second one, the reason for the `||` is that some streams incorrectly set VOD in the M3U when the stream is live. So even if m_isRealTimeStream is wrongly false checking the duration will validate it. Or that was the thought process anyway.

I don't see why this makes your streams switch time faster though. I would like to understand that a bit better.

**Comment by vpeter4** [comment]
I'm no specialist on streaming but maybe my HLS streams are little different than others (which I really doubt).
I always set `is_realtime_stream = false` and I get channel playing almost immediately after pressing OK button. If I use default settings then after pressing OK it takes more than I second to get any image on TV - I get black screen in between.
And I use `is_realtime_stream = false` for live playback and for past shows.
Which open a question: what does have catchup to do in both addons when I select one channel for live streaming?

**Comment by phunkyfish** [comment]
Hmmm, setting `is_realtime_stream` to `false` should take more time to open the file and not less as it would also read the streaminfo for live streams. Maybe it's different for HLS. I don't think your changes will cause any issue anyway so would you like to create some PRs for them? It makes sense the user should be able to override any setting from the M3U.

> Which open a question: what does have catchup to do in both addons when I select one channel for live streaming?

Can you elaborate further on the question? It doesn't quite make sense to me.

**Comment by vpeter4** [comment]
I can send PR. But I assume only for pvr.iptvsimple?
As I wrote I don't really understand what is going on that's why I didn't send PR initially.

Regarding my last question: When I select to play one live channel (not some old show) it still goes through CatchupController.cpp.

**Comment by vpeter4** [comment]
Now I remembered: I have this issue for long time. And This PR had something to do with it. And I mentioned realtime there too.
https://github.com/xbmc/xbmc/pull/14193

And I forgot on another issue: When I select one channel to play addon inputstream.ffmpegdirect get channel m3u8 twice. And server returns same data. I fixed this issue on Kodi Leia but not yet on Matrix.

**Comment by phunkyfish** [comment]
PRs welcome 😉

**Comment by phunkyfish** [comment]
> I can send PR. But I assume only for pvr.iptvsimple?
> As I wrote I don't really understand what is going on that's why I didn't send PR initially.
> 
> Regarding my last question: When I select to play one live channel (not some old show) it still goes through CatchupController.cpp.

I think you would need both. Because for a live stream ffmpegdirect would override the property with the duration check.

**Comment by phunkyfish** [comment]
Yes, everything goes through catchup controller. The reason being it needs to configure the other properties to allow seeking back from live

**Comment by vpeter4** [comment]
So what should I send in the PR for inputstream.ffmpegdirect? Removed `|| m_pFormatContext->duration <= 0` ?
I don't want to break something just to get my thing working :)  Which will work with my local patch too.

**Comment by phunkyfish** [comment]
I think replace the || with &&. The addon should honour the is_realtime_stream value.

**Comment by vpeter4** [comment]
Good then. Will try this change here and if everything be ok I send PR.

But I think then checking for duration is unnecessary with using && ?

**Comment by phunkyfish** [comment]
The duration check is still good as it validates if a stream is actually live.

**Comment by vpeter4** [comment]
I will write my last finding here just for completeness.

https://github.com/xbmc/xbmc/pull/16355/files#diff-4b73a3a0982479ec64d6aba7b0f64380R262

Why there are two `avformat_open_input()` calls just with different context flags? In my case it opens same **m3u8** link for a channel and and the server in both cases returns same data. Seems redundant and useless?

**Comment by phunkyfish** [comment]
That’s how ffmpeg works. You open the stream to probe some of the required values to be able to play the stream then open it again with those values.

**Comment by phunkyfish** [comment]
If you have found an efficiency that improves performance for a certain stream type we can add it as an option easily enough.

**Comment by vpeter4** [comment]
As I wrote yesterday take my writing with a reserve.

At least in my case both avformat_open_input() calls open a link which doesn't open actual video stream but it opens M3U8 for a channel. And link returns content like
```
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 30 Jun 2020 09:00:52 GMT
Content-Type: application/vnd.apple.mpegurl
Content-Length: 1388
Connection: keep-alive
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: CONNECT, DELETE, GET, HEAD, OPTIONS, POST, PUT, TRACE
Access-Control-Allow-Origin: *
Cache-Control: no-store, no-cache, must-revalidate
Expires: 0
Pragma: no-cache
Set-Cookie: sessionId=....;path=/
X-Mnd-Stream-Accepted-On: ......
X-Mnd-Stream-Accepted-Reason: Pre-init 2. Sender get 2. Player start 2.
X-Frame-Options: DENY
X-Content-Type-Options: nosniff

#EXTM3U
#EXT-X-VERSION:7
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-STREAM-INF:BANDWIDTH=7096000,FRAME-RATE=25.000,RESOLUTION=1920x1080
https://some-server/stream?extra-data......&player=m3u8"
```

Link from this first M3U8 returns another M3U8 for actual segments like
```
#EXTM3U
#EXT-X-VERSION:7
#EXT-X-TARGETDURATION:6
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-DISCONTINUITY-SEQUENCE:0

#EXTINF:6.000,
https://some-server/stream/fragment/ts/live/?session=...&offset=276860&pointeroffset=10&fragmentlength=6000
#EXTINF:6.000,
https://some-server/stream/fragment/ts/live/?session=...&offset=276861&pointeroffset=11&fragmentlength=6000
#EXTINF:6.000,
https://some-server/stream/fragment/ts/live/?session=...&offset=276862&pointeroffset=12&fragmentlength=6000
```

So I see no reason why initial M3U8 should be opened twice if in both cases get same data. I just partially reverted PR from above and everything is still good.

Maybe there should be some check what we are actually opening?

**Comment by phunkyfish** [comment]
I think that HLS might be a special case. I think we could add this as a configurable option so users could set this if they want. It may not work for all HLS streams but it will save on switch time so is a valid option.

If you can come up with a minimal change PR for this (separate to the other PR) we could also try and upstream the change to Kodi. We can ask Fernet what he thinks of it too. We can't just partially undo the previous commits as they fix other long running issues for TS streams.

**Comment by vpeter4** [comment]
I checked _FFmpegStream::GetFFMpegOptionsFromInput()_ function and obviously nothing happen there in my case :)

I think one global variable could work just fine. Similar as **Probe for FPS** ? But exactly the same code is also used in Kodi itself so I think it should be handled differently (more generic way)? Obviously I'm interested only for the code in this addon :-)

Maybe checking the m3u8 extension of the url? Like `http://some-server/path/stream.m3u8?arguments` Not sure how HLS streams are named in general.

**Comment by phunkyfish** [comment]
For this addon you can set the manifest_type property to hls and them set a member variable in the constructor initialiser list. This should automatically be set from iptvsimple so only a change is needed in this addon.

**Comment by phunkyfish** [comment]
Not sure what you should call the variable. Something more generic would be good as it may benefit other streams apart from HLS.

If you get it working I can add an additional commit to allow it to be set via a property and addon setting.

**Comment by phunkyfish** [comment]
It would also be nice to know the switching time improvement you get with each change. Maybe both combined could a performance setting in the addon to make it easy for less experienced users to use.

**Comment by vpeter4** [comment]
Switching time improvement is more than a second with both PR's which obey realtime information (set to false). That's why it is very noticeable.
The last change opening same link twice is not that important and depends on a remote server reaction. But it is still more than 100msec.

Regarding the third PR I need to look how to proceed. Not sure if ever will be changed. But please keep it on your todo list.

**Comment by phunkyfish** [comment]
If you can hack a working version of the 3rd PR that only works for HLS I can use that to create a proper PR for it.

Maybe something as simple as this might work:

```cpp
  if (result < 0)
  {
    //m_pFormatContext->flags |= AVFMT_FLAG_PRIV_OPT;
    //if (avformat_open_input(&m_pFormatContext, strFile.c_str(), iformat, &options) < 0)
    //{
    //  Log(LOGLEVEL_DEBUG, "Error, could not open file %s", CURL::GetRedacted(strFile).c_str());
    //  Dispose();
    //  av_dict_free(&options);
    //  return false;
    //}

    //av_dict_free(&options);
    //avformat_close_input(&m_pFormatContext);
    m_pFormatContext = avformat_alloc_context();
    m_pFormatContext->interrupt_callback = int_cb;
    m_pFormatContext->flags &= ~AVFMT_FLAG_PRIV_OPT;
    options = GetFFMpegOptionsFromInput();
    av_dict_set_int(&options, "load_all_variants", 0, AV_OPT_SEARCH_CHILDREN);

    if (avformat_open_input(&m_pFormatContext, strFile.c_str(), iformat, &options) < 0)
    {
      Log(LOGLEVEL_DEBUG, "Error, could not open file (2) %s", CURL::GetRedacted(strFile).c_str());
      Dispose();
      av_dict_free(&options);
      return false;
    }
  }
```

If you can test it happy to implement it properly.

**Comment by vpeter4** [comment]
Yes, above patch works and it is similar to what I'm using.

Just one note: **m_pFormatContext** doesn't need to be allocated again because it is already allocated in **FFmpegStream::Open()** before calling **FFmpegStream::OpenWithFFmpeg()**.

**Comment by phunkyfish** [comment]
Ah, yes. Makes sense.

**Comment by vpeter4** [comment]
It was again time to check how Kodi Matrix and PVR is working and I still have one issue with this commit: https://github.com/xbmc/inputstream.ffmpegdirect/commit/aa6c38c34373b2ca3a8c39e564691ec9562f3433
Here https://github.com/xbmc/inputstream.ffmpegdirect/commit/aa6c38c34373b2ca3a8c39e564691ec9562f3433#diff-4f3ba8e0c3f93ccca0d212788c71d1d1e54645386e40955fa41de10be4a3bdccR906
we have
`if (!kodi::GetSettingBoolean("useFastOpenForManifestStreams") || m_manifestType.empty())`
which means that even if `useFastOpenForManifestStreams` is `true` the code below is still execute because `m_manifestType` is `empty`.
The only option for me is to set `inputstream.ffmpegdirect.manifest_type=hls` in m3u8 playlist. Which is something I would like to avoid from start and I though the `useFastOpenForManifestStreams` would take care of it. Seems at the time in june when I was testing this solution the original code didn't have this second condition. Or maybe I missed something.

If not anything else I would like to know what purpose this second condition has?
One option would be to set `m_manifestType` to `hls` if `m_mimeType` means `HLS`.

Or maybe using `&&` instead of `||` ?
`if (!kodi::GetSettingBoolean("useFastOpenForManifestStreams") && m_manifestType.empty())`

**Comment by phunkyfish** [comment]
There should be no reason why manifest type is not set for an HLS stream.

**Comment by vpeter4** [comment]
From where? Automatically or manually in pvr.iptvsimple from m3u8?

What is the purpose useFastOpenForManifestStreams ? Seems it does not do what is intended?

**Comment by phunkyfish** [comment]
It should be set automatically from iptvsimple.

In `StreamUtils.cpp` in `SetFFmpegDirectManifestTypeStreamProperty()`

**Comment by phunkyfish** [comment]
If it's not working we should figure out why that property is not set as I believe the code is correct.

**Comment by vpeter4** [comment]
You are right: everything is ok. I was checking which options I need to set and I set default inputstream in pvr.iptvsimple:
`    <setting id="defaultInputstream">inputstream.ffmpegdirect</setting>`
And this doesn't set manifest type value. Removing it does the job.
Thanks for the response.

**Comment by phunkyfish** [comment]
NP
