### ISSUE TITLE
Timeshift segment file leftovers

### ISSUE THREAD

**Issue by puenktchen** [xbmc/inputstream.ffmpegdirect#61]
Occasionally after stoping a PVR Simple channel stream with active timeshifting,
some segment files are left in the timeshift folder.
Maybe you should create a slight delay after stoping timeshift and before cleanup the timeshift files.

**Comment by phunkyfish** [comment]
What platform is this on? Can you capture a debug log of this happening? That might be tricky as this is occasional.

**Comment by puenktchen** [comment]
> What platform is this on? Can you capture a debug log of this happening? That might be tricky as this is occasional.

This was on Windows. I'll try to capture a log file.

**Comment by phunkyfish** [comment]
Can this be closed?

**Comment by puenktchen** [comment]
Fixed through other commit. Thanks.
