### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Durlyn** [xbmc/inputstream.ffmpegdirect#73]
when compiling the addon, such an error /inputstream.ffmpegdirect/src/stream/FFmpegStream.cpp:201:85: error: "MAX_STREAM_COUNT" is not an element "INPUTSTREAM_IDS". 
OS: Fedora 32.
addon version - last from git.

**Comment by phunkyfish** [comment]
Please wait a few days. The inputstream API is currently being updated. I would expect a PR for this addon soon and it should work after that.

**Comment by Durlyn** [comment]
thanks. everything worked.
