### ISSUE TITLE
v1.18.2 Kodi crashes (kodi 19 beta1, android 32bits)

### ISSUE THREAD

**Issue by Gregsr** [xbmc/inputstream.ffmpegdirect#81]
Since I have updated the addon (1 hour ago), kodi closes (crashes?) directly when I play a channel.
Here is the log https://paste.kodi.tv/wosepicuko.kodi
Need a debug log?

**Comment by phunkyfish** [comment]
Does it crash on a 64bit OS? What was the version you had installed prior to that? It was only a log line changed in that release so unlikely it caused the crash.

Also, elementum is a banned addon. Please remove it and then create a debug log if you would like support.

**Comment by Gregsr** [comment]
Yes on 64bit too.
Previously, it was the v1.18.1. 
Here are the debugs for 32 (android) and 64bit (win7)
[Win7_64bit.log](https://github.com/xbmc/inputstream.ffmpegdirect/files/5611767/Win7_64bit.log)
[Android_32bit.log](https://github.com/xbmc/inputstream.ffmpegdirect/files/5611769/Android_32bit.log)

Is there a list of banned addons available?

**Comment by phunkyfish** [comment]
Sure: the list is not comprehensive: https://kodi.wiki/view/Official:Forum_rules/Banned_add-ons

But if you go to your log link you will see any addons in orange would be on the banned list.

Can you detail exact steps on how to reproduce this? If you need to send me example URLs you can use gitter.im.

**Comment by Gregsr** [comment]
1. Launch Kodi :)
2. Open TV
3. Play a channel
4. Kodi crashes

If I send you URLs, I don't know if my IPTV provider lets you test because of different IP adresses. We can test if needed.

No issue with VOD (http://...mkv)

**Comment by phunkyfish** [comment]
Try sending me some URLs in the M3U format you use and we can see what happens. If they don’t work we can try something else.

**Comment by phunkyfish** [comment]
I have used very test url I have but can’t reproduce this crash. I guess we will have to try yours.

**Comment by alexandrgoryachko** [comment]
I confirm @Gregsr message. I have the same issue on Windows 10(64bit). When in the PVR IPTV Simple Client enabled timeshift and I try to open any channel the Kodi crashes and closes.

**Comment by phunkyfish** [comment]
This issue was only on android so far. Interesting that you also have it on windows.

**Comment by Gregsr** [comment]
> This issue was only on android so far. Interesting that you also have it on windows.

I have same issue on Win7 64bit. I uploaded a debug file (see above)

**Comment by phunkyfish** [comment]
Can you both check if this issue is because timeshift is enabled or not?

**Comment by alexandrgoryachko** [comment]
Yes, it happens only when in settings of the PVR IPTV Simple Client enabled timeshift. If I disable timeshift - Kodi works fine.

**Comment by phunkyfish** [comment]
Ok, please try and reproduce once beta2 is released. I couldn’t reproduce this on windows today.

You should be able to download beta2 in the next day or so. Or grab this test build I created today: https://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20201207-888760df-win64-debug-x64.exe

**Comment by phunkyfish** [comment]
I think beta2 will fix the crash issue for android also.

**Comment by alexandrgoryachko** [comment]
Yes, looks like for the build above everything works fine.

**Comment by phunkyfish** [comment]
Beta2 is also up for download now.

**Comment by Gregsr** [comment]
- Beta2 on Android TV 9 32bit and v1.18.2: no crash
- Beta2 on Win7 64bit and v1.18.2: no crash
- No possibility to test on Android 64bit

**Comment by phunkyfish** [comment]
No worries. I think it probably safe enough to assume Android64bit is ok too.
