### ISSUE TITLE
Doesn't compile on Aaarch64

### ISSUE THREAD

**Issue by ivanich** [xbmc/inputstream.ffmpegdirect#89]
System is Archlinuxarm
Linux raspberrypi 5.10.16-3-ARCH #1 SMP PREEMPT Tue Feb 16 11:41:10 MST 2021 aarch64 GNU/Linux

Fails at link stage
```
[ 87%] Building CXX object CMakeFiles/inputstream.ffmpegdirect.dir/src/utils/DiskUtils.cpp.o
[ 93%] Building CXX object CMakeFiles/inputstream.ffmpegdirect.dir/src/utils/FilenameUtils.cpp.o
[100%] Linking CXX shared library inputstream.ffmpegdirect.so
/home/alarm/aur/kodi-addon-inputstream-ffmpegdirect-any/src/inputstream.ffmpegdirect-1.19.2-Matrix/build/build/depends/lib/libhogweed.a(bignum.o): in function `nettle_mpz_sizeinbase_256_s':
/home/alarm/aur/kodi-addon-inputstream-ffmpegdirect-any/src/inputstream.ffmpegdirect-1.19.2-Matrix/build/build/nettle/src/nettle/bignum.c:61:(.text+0xd8): relocation truncated to fit: R_AARCH64_LD64_GOTPAGE_LO15 against symbol `__gmpz_sizeinbase' defined in .text section in /home/alarm/aur/kodi-addon-inputstream-ffmpegdirect-any/src/inputstream.ffmpegdirect-1.19.2-Matrix/build/build/depends/lib/libgmp.a(sizeinbase.o)
/usr/bin/ld: /home/alarm/aur/kodi-addon-inputstream-ffmpegdirect-any/src/inputstream.ffmpegdirect-1.19.2-Matrix/build/build/nettle/src/nettle/bignum.c:61: warning: too many GOT entries for -fpic, please recompile with -fPIC
collect2: error: ld returned 1 exit status
make[5]: *** [CMakeFiles/inputstream.ffmpegdirect.dir/build.make:322: inputstream.ffmpegdirect.so.1.19.2] Error 1
make[4]: *** [CMakeFiles/Makefile2:96: CMakeFiles/inputstream.ffmpegdirect.dir/all] Error 2
make[3]: *** [Makefile:171: all] Error 2
make[2]: *** [CMakeFiles/inputstream.ffmpegdirect.dir/build.make:132: inputstream.ffmpegdirect-prefix/src/inputstream.ffmpegdirect-stamp/inputstream.ffmpegdirect-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:287: CMakeFiles/inputstream.ffmpegdirect.dir/all] Error 2
make: *** [Makefile:103: all] Error 2
```

**Comment by phunkyfish** [comment]
Does the gmp library build with libhogweed on your OS?

If so what version of gmp and nettle builds correctly?

**Comment by ivanich** [comment]
Long story, 1 raspberrypi4 and 2 sdcards, first is archlinux armv7h(32bit) and second one is archlinux Aarch64(64bits). I was able to successfully build inputstream.ffmpegdirect with this PKGBUILD https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kodi-addon-inputstream-ffmpegdirect-any on  archlinux armv7h(32bit), however the same procedure on the archlinux Aarch64(64bits) is failed with same PKGBUILD. Basically both OS has nearly the same set of packages with same versions but different arch obviously. As for gmp and libhogweed i believe both were successfully built as dependencies for inputstream.ffmpegdirect(even log I posted above shows that it tries to link libhogweed and libgmp from ffmegdirect build dir). On both OS I have gmp 6.2.1-1 and nettle(which provides libhogweed) 3.7.1-1 32bit and 64bit respectively - but I guess it doesn't matter which versions of gmp and nettle is installed.

**Comment by phunkyfish** [comment]
So if not on linux it is built against gmp 6.2 and nettle 3.6. So you are in unchartered territory.

What about: ```bignum.c:61: warning: too many GOT entries for le/bignum.c:61: warning: too many GOT entries for -fpic, please recompile with -fPIC```

**Comment by ivanich** [comment]
Found some links regarding R_AARCH64_LD64_GOTPAGE_LO15, anyway it wasn't very useful
https://bugs.mysql.com/bug.php?id=98798
https://jira.automotivelinux.org/browse/SPEC-658?page=com.atlassian.jira.plugin.system.issuetabpanels%3Achangehistory-tabpanel

Can we bump nettle, gnutls and gmp versions to the latest just in case it'll change anything?

**Comment by phunkyfish** [comment]
I can but it can be several days work to get it to build, redo patches etc. depending on what's changed so it would be a while before I have the time. When I get it PR'd I can let you know and you can try that branch. I wouldn't want to release it unless we are sure it helps as Matrix is only just out.

**Comment by ivanich** [comment]
Another option would be simply do as stated in the error message, enable -fPIC for all dependencies, or at least for gmp and nettle

**Comment by lrusak** [comment]
Kodi depends force using -fPIC for arm/aarch64 builds

See: https://github.com/xbmc/xbmc/blob/master/tools/depends/configure.ac#L325

**Comment by phunkyfish** [comment]
I’m not sure if that applies to binary add-one though. Or it may be that the OS libraries are missing this.

**Comment by lrusak** [comment]
from a jenkins aarch64 linux master build

```
/usr/bin/aarch64-linux-gnu-g++ -fPIC -fPIC -DPIC -Og -g -D_DEBUG   -fPIC -DPIC -DNDEBUG=1 -Os   -Wl,-Bsymbolic -L/home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/target/binary-addons/aarch64-linux-gnu-debug/build/depends/lib -lavfilter -pthread -lm -lavformat -lm -lxml2 -lz -lm -lbz2 -lz -lgnutls -pthread -lgmp -latomic -ldl -lhogweed -lgmp -lnettle -lavcodec -pthread -liconv -lm -llzma -lzvbi -lm -lpng -lpthread -lm /home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/target/binary-addons/aarch64-linux-gnu-debug/build/depends/lib/libiconv.a -lz -lm -lz -lswscale -lm -lswresample -lm -lpostproc -lm -lavutil -pthread -lm -Wl,-rpath-link=/home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/xbmc-depends/aarch64-linux-gnu-debug/lib -shared -Wl,-soname,inputstream.ffmpegdirect.so.19.0 -o inputstream.ffmpegdirect.so.1.19.2 CMakeFiles/inputstream.ffmpegdirect.dir/src/StreamManager.cpp.o CMakeFiles/inputstream.ffmpegdirect.dir/src/stream/DemuxStream.cpp.o CMakeFiles/inputstream.ffmpegdirect.dir/src/stream/FFmpegCatchupStream.cpp.o CMakeFiles/inputstream.ffmpegdirect.dir/src/stream/FFmpegLog.cpp.o CMakeFiles/inputstream.ffmpegdirect.dir/src/stream/FFmpegStream.cpp.o CMakeFiles/inputstream.ffmpegdirect.dir/src/stream/CurlCatchupInput.cpp.o CMakeFiles/inputstream.ffmpegdirect.dir/src/stream/CurlInput.cpp.o CMakeFiles/inputstream.ffmpegdirect.dir/src/stream/TimeshiftBuffer.cpp.o CMakeFiles/inputstream.ffmpegdirect.dir/src/stream/TimeshiftSegment.cpp.o CMakeFiles/inputstream.ffmpegdirect.dir/src/stream/TimeshiftStream.cpp.o CMakeFiles/inputstream.ffmpegdirect.dir/src/stream/url/URL.cpp.o CMakeFiles/inputstream.ffmpegdirect.dir/src/stream/url/UrlOptions.cpp.o CMakeFiles/inputstream.ffmpegdirect.dir/src/stream/url/Variant.cpp.o CMakeFiles/inputstream.ffmpegdirect.dir/src/utils/DiskUtils.cpp.o CMakeFiles/inputstream.ffmpegdirect.dir/src/utils/FilenameUtils.cpp.o  /home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/target/binary-addons/aarch64-linux-gnu-debug/build/depends/lib/libz.a /home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/target/binary-addons/aarch64-linux-gnu-debug/build/depends/lib/libbz2.a /home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/target/binary-addons/aarch64-linux-gnu-debug/build/depends/lib/libavcodec.a /home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/target/binary-addons/aarch64-linux-gnu-debug/build/depends/lib/libavfilter.a /home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/target/binary-addons/aarch64-linux-gnu-debug/build/depends/lib/libavformat.a /home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/target/binary-addons/aarch64-linux-gnu-debug/build/depends/lib/libavutil.a /home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/target/binary-addons/aarch64-linux-gnu-debug/build/depends/lib/libswscale.a /home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/target/binary-addons/aarch64-linux-gnu-debug/build/depends/lib/libswresample.a /home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/target/binary-addons/aarch64-linux-gnu-debug/build/depends/lib/libpostproc.a -L/home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/target/binary-addons/aarch64-linux-gnu-debug/build/depends/lib -lavfilter -pthread -lm -lavformat -lm -lxml2 -lz -lm -lbz2 -lz -lgnutls -pthread -lgmp -latomic -ldl -lhogweed -lgmp -lnettle -lavcodec -pthread -liconv -lm -llzma -lzvbi -lm -lpng -lpthread -lm /home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/target/binary-addons/aarch64-linux-gnu-debug/build/depends/lib/libiconv.a -lz -lm -lz -lswscale -lm -lswresample -lm -lpostproc -lm -lavutil -pthread -lm -lavformat -lxml2 -lz -lbz2 -lgnutls -lgmp -latomic -ldl -lhogweed -lnettle -lavcodec -liconv -llzma -lzvbi -lpng -lpthread /home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/target/binary-addons/aarch64-linux-gnu-debug/build/depends/lib/libiconv.a -lswscale -lswresample -lpostproc -lavutil
```

**Comment by wsnipex** [comment]
I suspect this is a "standard linux build" against system libraries.
In that case the missing -fpic is on the arch linux side.

edit: and bumping dependencies here won't make a difference at all, since they are not used.

**Comment by ivanich** [comment]
> edit: and bumping dependencies here won't make a difference at all, since they are not used.

So why we building all those deps ffmpeg, gnutls, nettle and others if they are not used? According to the build error message I think the problem might be in the archlinux aarch64 binutils package since it fails on the link step. From another side it looks like this error is not a bug but a limitation for the aarch64 itself, I mean R_AARCH64_LD64_GOTPAGE_LO15 - so the question is how we can bypass that?

**Comment by wsnipex** [comment]
distro packages are not supposed to be built with our depends system.
You should build it against the Kodi headers from the kodi-git-dev package and dependencies from system.

Example: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kodi-addon-pvr-hts

**Comment by ivanich** [comment]
I'm not trying to build distro packages at all :)
But this particular addon has dependencies here https://github.com/xbmc/inputstream.ffmpegdirect/tree/Matrix/depends/common and it means that it doesn't use distro packages at all except gcc, binutils and few other apps required for actually build a package.

**Comment by wsnipex** [comment]
the addon always requires those dependencies. The difference is where they come from.
There are 2 ways to build binary addons for kodi:
1. kodi's own depends system, where all dependencies are downloaded and built automatically.
This is the only way for most platforms that do not provide them for the OS. e.g. android, ios, osx
2. Using system/OS provided libraries.
This is the recommended and typical way on linux.

You are attempting 1, while you probably should use 2, even if you don't want distro packaging

**Comment by ivanich** [comment]
So dirty workaround is lto, I was able to build it with -flto cflag

**Comment by ghost** [comment]
How did you get this to compile? I tried adding options(lto) to the PKGBUILD but it didn't work. I also tried adding -fpic then -flto to the cmake command in the makepkg.conf @ivanich
